plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 6
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "CHICF"
email: 3342519035@qq.com
description: ""
github:
  username: chic-black
swiftype:
  searchId: BEDnQJ6-j-rMQaksZbdE
gitment:
    repo: chic-black.github.io
    client_id: a6e5d0e08bdde9aed501
    client_secret: 9608273e351e7f153f879add258786f808f331a4

url: "https://chic-black.github.io"
imgrepo: "https://chic-black.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

